// good catch 的第一个参数 error 没有被重新赋值了
try {
    // do something
} catch (e) {
    console.error(e);
}